# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    codeCoverageToolOption: 'cobertura'
    #codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
    #codeCoverageClassFilesDirectories: # Optional
    #codeCoverageSourceDirectories: # Optional
    #codeCoverageFailIfEmpty: false # Optional


- script: | 
   echo Write your commands here
   echo Hello world
   echo %cd%
   cd CP
   echo %cd%
   echo %System.AccessToken%
   dotnet CoveragePublisher.Console.exe D:\a\1\s\target\site\cobertura\coverage.xml
  displayName: 'Command Line Script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- script: |
   echo Write your commands here
   
   echo Hello world
   
   dotnet CoveragePublisher/CoveragePublisher.Console.dll coverage.cobertura.xml
  displayName: 'Command Line Script 2'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
